### PR TITLE
feat: meili v1.1.1

### PR DESCRIPTION
**Pull request by vknabel**
Requires https://github.com/metal-stack/releases/pull/114

### CODE REVIEW

**Comment by majst01** [comment]
Not sure if we should put another entry into the release vector: https://github.com/metal-stack/releases/blob/master/release.yaml#L189

**Comment by vknabel** [comment]
Yes, we should. I'll add it. Somehow I thought the release mapping would be in the mini-lab. I'll add it.

**Review by majst01 — APPROVED** [review]

**Comment by Gerrit91** [comment]
When the proper container image versions are already shipped with their chart releases, why do we manage them individually now? I can understand overriding these optionally but the default version should come from their chart releases.

**Comment by vknabel** [comment]
The Multisearch we use to list auditing traces is a v1.1 feature, but the latest chart release still defaults to v1.0

**Pull request merged**
